import { site, services, team, articles } from './data.mjs'
import { layout, pageHero, serviceList, articleGrid, cta, href, head, header, footer } from './templates.mjs'

export const pages=new Map()

pages.set('',layout({
  title:'Nexo Contabilidade em São Raimundo Nonato – PI',
  desc:'Contabilidade demonstrativa para empresas e empreendedores, com proximidade, organização e apoio à gestão.',
  body:`<section class="hero"><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow">Contabilidade próxima e organizada</span><h1>Conectamos números, rotina e decisões.</h1><p>Uma proposta contábil feita para empresas que precisam compreender melhor seus dados, prazos e próximos passos.</p><div class="actions"><a class="btn btn-main" href="${href('contato/')}">Falar com a equipe</a><a class="text-link" href="${href('servicos/')}">Ver todos os serviços →</a></div></div><figure class="hero-photo"><img src="${site.images.hero}" alt="Equipe reunida em ambiente de trabalho colaborativo" width="1400" height="1000" fetchpriority="high"><figcaption><strong>Clareza para decidir.</strong><span>Processos bem definidos e informação acessível.</span></figcaption></figure></div><div class="container hero-strip"><div><b>01</b><span>Documentos organizados</span></div><div><b>02</b><span>Prazos acompanhados</span></div><div><b>03</b><span>Informação útil</span></div></div></section><section class="section"><div class="container editorial-head"><div><span class="eyebrow">Serviços</span><h2>O apoio certo em cada fase da empresa.</h2></div><p>Da abertura às rotinas mensais, cada serviço parte da realidade do negócio e das informações disponíveis.</p></div><div class="container">${serviceList()}</div></section><section class="section olive"><div class="container split"><figure class="office-photo"><img src="${site.images.office}" alt="Escritório contemporâneo com mesas e iluminação natural" width="1400" height="1000" loading="lazy" decoding="async"></figure><div class="copy"><span class="eyebrow light">O escritório</span><h2>Menos linguagem complicada. Mais compreensão.</h2><p>A Nexo Contabilidade é um projeto fictício criado para apresentar uma experiência digital diferente: mais editorial, humana e próxima do empresário.</p><ul><li>Atendimento consultivo</li><li>Rotinas padronizadas</li><li>Comunicação objetiva</li><li>Apoio à gestão</li></ul><a class="btn btn-light" href="${href('escritorio/')}">Conhecer a Nexo</a></div></div></section><section class="section"><div class="container editorial-head"><div><span class="eyebrow">Equipe</span><h2>Pessoas que traduzem a rotina contábil.</h2></div><a class="text-link" href="${href('equipe/')}">Conhecer a equipe →</a></div><div class="container team-preview">${team.map(p=>`<article><img src="${p.image}" alt="${p.alt}" width="900" height="1100" loading="lazy" decoding="async"><div><span class="meta">${p.role}</span><h3>${p.name}</h3></div></article>`).join('')}</div></section><section class="section cream"><div class="container editorial-head"><div><span class="eyebrow">Conteúdo</span><h2>Leituras para quem administra uma empresa.</h2></div><p>Conteúdos demonstrativos sobre organização, tributos e gestão.</p></div><div class="container">${articleGrid()}</div></section>${cta}`
}))

pages.set('escritorio/',layout({title:'O Escritório | Nexo Contabilidade',desc:'Conheça a proposta de atendimento e organização da Nexo Contabilidade.',route:'escritorio/',active:'office',body:`${pageHero('Contabilidade feita para aproximar.','Uma proposta contemporânea que conecta rotina contábil, comunicação e gestão empresarial.',[['escritorio/','Escritório']])}<section class="section"><div class="container split reverse"><div class="copy dark-copy"><span class="eyebrow">Nossa proposta</span><h2>Informação que faz sentido para quem empreende.</h2><p>A Nexo Contabilidade é fictícia e foi criada para portfólio. Seu conceito combina atendimento próximo, organização de documentos e uma comunicação mais simples.</p><p>O trabalho demonstrativo começa pelo entendimento do negócio, definição de rotinas e acompanhamento dos principais prazos.</p><ul><li>Clareza na comunicação</li><li>Processos definidos</li><li>Confidencialidade</li><li>Visão empresarial</li></ul></div><figure class="office-photo tall"><img src="${site.images.meeting}" alt="Profissionais discutindo informações empresariais em reunião" width="1400" height="1200"></figure></div></section>${cta}`}))

pages.set('servicos/',layout({title:'Serviços | Nexo Contabilidade',desc:'Conheça os serviços contábeis demonstrativos da Nexo Contabilidade.',route:'servicos/',active:'services',body:`${pageHero('Serviços contábeis','Soluções para abertura, regularização e acompanhamento das principais rotinas empresariais.',[['servicos/','Serviços']])}<section class="section"><div class="container">${serviceList()}</div></section>${cta}`}))

for(const [slug,title,desc] of services){
  pages.set(`servicos/${slug}/`,layout({title:`${title} | Nexo Contabilidade`,desc:`${desc} Atendimento demonstrativo em São Raimundo Nonato – PI.`,route:`servicos/${slug}/`,active:'services',body:`${pageHero(title,desc,[['servicos/','Serviços'],[`servicos/${slug}/`,title]])}<section class="section"><div class="container prose"><span class="eyebrow">Como funciona</span><h2>Organização antes da execução.</h2><p>${desc}</p><p>O atendimento considera atividade, porte, documentos disponíveis, obrigações atuais e objetivos do negócio. As orientações dependem da análise do caso concreto.</p><h2>Etapas comuns</h2><ol><li>Levantamento das informações</li><li>Conferência dos documentos</li><li>Definição de prazos e responsáveis</li><li>Acompanhamento das providências</li></ol><div class="notice"><strong>Projeto demonstrativo</strong><p>Este conteúdo é ilustrativo e não substitui orientação profissional baseada nos dados reais da empresa.</p></div></div></section>${cta}`}))
}

pages.set('equipe/',layout({title:'Equipe | Nexo Contabilidade',desc:'Conheça a equipe fictícia da Nexo Contabilidade.',route:'equipe/',active:'team',body:`${pageHero('Equipe','Profissionais fictícios criados para demonstrar a apresentação institucional de um escritório contábil.',[['equipe/','Equipe']])}<section class="section"><div class="container team-page">${team.map((p,i)=>`<article class="person-row ${i%2?'reverse':''}"><img src="${p.image}" alt="${p.alt}" width="900" height="1100"><div><span class="meta">${p.role}</span><h2>${p.name}</h2><p>${p.bio}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div></div></article>`).join('')}<div class="notice">Nomes, registros, formações e fotografias são ilustrativos.</div></div></section>${cta}`}))

pages.set('artigos/',layout({title:'Artigos | Nexo Contabilidade',desc:'Conteúdos informativos sobre contabilidade, gestão e empreendedorismo.',route:'artigos/',active:'articles',body:`${pageHero('Artigos','Conteúdos gerais para empresários, MEIs e profissionais. Não substituem análise individual.',[['artigos/','Artigos']])}<section class="section cream"><div class="container">${articleGrid()}</div></section>`}))

for(const a of articles){
  pages.set(`artigos/${a.slug}/`,layout({title:`${a.title} | Nexo Contabilidade`,desc:a.excerpt,route:`artigos/${a.slug}/`,active:'articles',type:'article',article:a,image:a.image,body:`${pageHero(a.title,a.excerpt,[['artigos/','Artigos'],[`artigos/${a.slug}/`,a.title]])}<article class="section"><div class="container prose"><p class="meta">${a.category} · <time datetime="${a.date}">${new Intl.DateTimeFormat('pt-BR').format(new Date(`${a.date}T12:00:00Z`))}</time> · ${a.read}</p><img class="article-cover" src="${a.image}" alt="${a.alt}" width="1200" height="800">${a.sections.map(([h,p])=>`<h2>${h}</h2><p>${p}</p>`).join('')}<div class="notice"><strong>Aviso</strong><p>Este artigo é informativo e demonstrativo. A decisão correta depende dos dados reais do contribuinte ou da empresa.</p></div><a href="${href('artigos/')}">← Voltar aos artigos</a></div></article>`}))
}

pages.set('contato/',layout({title:'Contato | Nexo Contabilidade',desc:'Conheça os canais demonstrativos da Nexo Contabilidade.',route:'contato/',active:'contact',body:`${pageHero('Contato','Envie uma breve descrição da sua necessidade para organizar o primeiro atendimento.',[['contato/','Contato']])}<section class="section"><div class="container contact-grid"><div class="contact-card wine"><span class="eyebrow light">Canais demonstrativos</span><h2>Fale com a Nexo</h2><p><strong>WhatsApp</strong><br><a href="https://wa.me/${site.whatsapp}" target="_blank" rel="noopener noreferrer">${site.phone}</a></p><p><strong>E-mail</strong><br><a href="mailto:${site.email}">${site.email}</a></p><p><strong>Endereço</strong><br>${site.address}</p><p><strong>Horário</strong><br>Segunda a sexta, das 8h às 18h</p></div><div class="contact-card"><span class="eyebrow">Antes do contato</span><h2>Organize as informações básicas.</h2><p>Informe o tipo de empresa, atividade, cidade, regime atual e principal dúvida. Não envie documentos pessoais neste projeto demonstrativo.</p><a class="btn btn-main" href="https://wa.me/${site.whatsapp}?text=${encodeURIComponent('Olá! Gostaria de informações sobre os serviços contábeis da Nexo.')}" target="_blank" rel="noopener noreferrer">Abrir WhatsApp</a></div></div></section>`}))

pages.set('politica-de-privacidade/',layout({title:'Política de Privacidade | Nexo Contabilidade',desc:'Política demonstrativa de privacidade da Nexo Contabilidade.',route:'politica-de-privacidade/',body:`${pageHero('Política de privacidade','Informações gerais sobre dados neste projeto demonstrativo.',[['politica-de-privacidade/','Privacidade']])}<section class="section"><div class="container prose"><h2>Natureza do projeto</h2><p>Este site não representa uma empresa real e não deve receber documentos fiscais, contábeis ou pessoais.</p><h2>Links externos</h2><p>O botão de WhatsApp direciona para serviço externo, sujeito às políticas da plataforma.</p><h2>Uso em produção</h2><p>Antes da publicação como site real, esta política deve ser ajustada às ferramentas, dados e finalidades utilizadas.</p></div></section>`}))

export const notFound=`${head({title:'Página não encontrada | Nexo Contabilidade',desc:'A página solicitada não foi encontrada.',route:'404/'})}<body data-prerendered="true">${header()}<main id="main-content">${pageHero('Página não encontrada','O endereço pode estar incorreto ou a página pode ter sido removida.',[['404/','Erro 404']])}<section class="section"><div class="container"><a class="btn btn-main" href="${href()}">Voltar ao início</a></div></section></main>${footer()}</body></html>`
export const admin=`${head({title:'Painel | Nexo Contabilidade',desc:'Área administrativa demonstrativa.',route:'admin/'})}<body><main class="admin"><section class="admin-card"><span class="eyebrow">Área administrativa</span><h1>Painel de conteúdo</h1><p>O projeto está em modo demonstrativo. A gestão dos arquivos é realizada pelo repositório GitHub.</p><a class="btn btn-main" href="https://github.com/RicardoRibeiro-Prof/nexo-contabilidade" target="_blank" rel="noopener noreferrer">Abrir repositório</a><p><a href="${href()}">← Voltar ao site</a></p></section></main></body></html>`
